#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 是三毛就好了

# Short bio or description (displayed in the header)
description: 一只行走在前端神坑的废仙女

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: http://image.baidu.com/search/detail?ct=503316480&z=0&ipn=d&word=%E4%B8%89%E6%AF%9B%E4%BD%9C%E5%AE%B6%E5%9B%BE%E7%89%87&step_word=&hs=0&pn=305&spn=0&di=72995627540&pi=0&rn=1&tn=baiduimagedetail&is=0%2C0&istype=0&ie=utf-8&oe=utf-8&in=&cl=2&lm=-1&st=undefined&cs=1938355435%2C2052013466&os=2594166436%2C1181761519&simid=4226125262%2C528080869&adpicid=0&lpn=0&ln=1947&fr=&fmq=1498813464909_R&fm=&ic=undefined&s=undefined&se=&sme=&tab=0&width=undefined&height=undefined&face=undefined&ist=&jit=&cg=&bdtype=0&oriquery=&objurl=http%3A%2F%2Fwww.qhdxw.com%2Fall%2Fuploads%2Fallimg%2F20160803%2F140117_242223.jpg&fromurl=ippr_z2C%24qAzdH3FAzdH3Fooo_z%26e3Bqi1xo_z%26e3Bv54AzdH3FwssfAzdH3Fv5gpjgp-dllcnmAzdH3F&gsm=10e&rpstart=0&rpnum=0

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: 13661431851@163.com
  facebook:
  flickr:
  github: sanmaomao
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://sanmaomao.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#
markdown: kramdown
highlighter: rouge
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
